// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHOfFmwM-5qSBDu9DEYx_Dx3uyrfcbxMg',
    appId: '1:451411050253:web:04739304a832fb03f6ba44',
    messagingSenderId: '451411050253',
    projectId: 'crypto-app-ca464',
    authDomain: 'crypto-app-ca464.firebaseapp.com',
    storageBucket: 'crypto-app-ca464.appspot.com',
    measurementId: 'G-RVWR8MYSES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAWcheoh7OVB0JwFjRk8LXe7IWGFzFXaY',
    appId: '1:451411050253:android:40beec36b7a66ec2f6ba44',
    messagingSenderId: '451411050253',
    projectId: 'crypto-app-ca464',
    storageBucket: 'crypto-app-ca464.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq81nN07ygpQ8fvNjaaaQ7I8ikADBr5mc',
    appId: '1:451411050253:ios:3e469e03d6c626cef6ba44',
    messagingSenderId: '451411050253',
    projectId: 'crypto-app-ca464',
    storageBucket: 'crypto-app-ca464.appspot.com',
    iosClientId: '451411050253-masa398bhjpf1d6aspoqp88g36fsekf1.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq81nN07ygpQ8fvNjaaaQ7I8ikADBr5mc',
    appId: '1:451411050253:ios:3e469e03d6c626cef6ba44',
    messagingSenderId: '451411050253',
    projectId: 'crypto-app-ca464',
    storageBucket: 'crypto-app-ca464.appspot.com',
    iosClientId: '451411050253-masa398bhjpf1d6aspoqp88g36fsekf1.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoApp',
  );
}
